### ISSUE TITLE
Error should be visible on the screen if a user try to enter a invalid value in creating a new single  retail bookings

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#126]

**Comment by suryaveer5320129** [comment]
```
2018-12-18 03:01:03 Sakha Cabs Xetrapal-Thread-155-[post] INFO : BookingResource: {u'drop_location': u'0-', u'product_id': u'SINGLTRP', u'passenger_mobile': u'7879764674567879645', u'cust_id': u'retail', u'pickup_location': u'Delhi-connaught dklsfgbir', u'booking_channel': u'webform', u'passenger_detail': u'browinie 7879764674567879645 browinie@thoko.fuchfuch', u'pickup_timestamp': u'2018-12-11T18:33:40.000Z'}
2018-12-18 03:01:03 Sakha Cabs Xetrapal-Thread-155-[post] INFO : BookingResource: Received Command single
2018-12-18 03:01:03 Sakha Cabs Xetrapal-Thread-155-[post] INFO : BookingResource: Trying to save single booking
2018-12-18 03:01:03 Sakha Cabs Xetrapal-Thread-155-[log_exception] ERROR : Exception on /booking/single [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/suryaveervm/sakhacabs/sakhacabs/api.py", line 336, in post
    if xpal.validate_booking_dict(respdict)['status']==True:
  File "/home/suryaveervm/sakhacabs/sakhacabs/xpal.py", line 280, in validate_booking_dict
    validation=utils.validate_dict(bookingdict,required_keys=required_keys,string_keys=string_keys,mobile_nums=mobile_nums)
  File "/home/suryaveervm/sakhacabs/sakhacabs/utils.py", line 34, in validate_dict
    validation['message']="{} too long a mobile number".format(bookingdict['passenger_mobile'])
NameError: global name 'bookingdict' is not defined
192.168.43.54 - - [18/Dec/2018 03:01:03] "POST /booking/single HTTP/1.1" 500 
```
